---
apiVersion: v1
kind: Namespace
metadata:
  name: ubitgpt-lite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubitgpt-lite
  name: ubitgpt-lite
  namespace: ubitgpt-lite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubitgpt-lite
  strategy: {}
  template:
    metadata:
      labels:
        app: ubitgpt-lite
    spec:
      containers:
        - env:
            - name: AZURE_OPENAI_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  key: AZURE_OPENAI_API_BASE_URL
                  name: env
            - name: AZURE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: AZURE_OPENAI_API_KEY
                  name: env
            - name: AZURE_OPENAI_DEPLOYMENT
              valueFrom:
                secretKeyRef:
                  key: AZURE_OPENAI_DEPLOYMENT
                  name: env
            - name: OPENAI_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_BASE_URL
                  name: env
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_KEY
                  name: env
          image: docker.io/blrchen/ubitgpt-lite:main
          name: ubitgpt-lite
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ubitgpt-lite
  name: ubitgpt-lite
  namespace: ubitgpt-lite
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: ubitgpt-lite